---

# Modified for fsulib.
# modernized pkg installation style 
 
- name: "Install NFS packages"
  apt:
    pkg: "{{ nfs_client_pkgs }}"
    state: present

- name: "Ensure mount points exist."
  file: 
    path: "{{ item.path }}"
    state: directory
  with_items: "{{ nfs_client_imports }}"

- name: "Mount NFS imports"
  mount: 
    fstype: nfs
    src: "{{ item.src }}" 
    path: "{{ item.path }}" 
    opts: "{{ item.opts }}" 
    state: mounted
  with_items: "{{ nfs_client_imports }}"
